#This is docker-compose for running DB for app, which runs from idea:
#- Connection URL:  jdbc:mysql://0.0.0.0:13306/DOCKERDB, login=root, password=root
#- App is available by http://localhost:8080/entitybus/post
version: "2.1"

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "23306:3306"
    volumes:
      - "./data/olympic_winners.sql:/docker-entrypoint-initdb.d/1.sql"
