FROM gradle:jdk11-hotspot

COPY . /project
RUN  cd /project && gradle bootJar

#this part for debug is moved into compose file, into "command":
#ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/project/build/libs/ag-grid-server-side--spring-boot--example-0.0.1-SNAPSHOT.jar"]
